#!/usr/bin/env bash

# yabai

cmd - 1 : yabai -m space --focus 1
cmd - 2 : yabai -m space --focus 2
cmd - 3 : yabai -m space --focus 3
cmd - 4 : yabai -m space --focus 4
cmd - 5 : yabai -m space --focus 5
cmd - 6 : yabai -m space --focus 6
cmd - 7 : yabai -m space --focus 7
cmd - 8 : yabai -m space --focus 8
cmd - 9 : yabai -m space --focus 9
cmd - 0 : yabai -m space --focus 10

cmd - h : yabai -m space --focus prev || yabai -m space --focus last
cmd - l : yabai -m space --focus next || yabai -m space --focus first

cmd - j : ~/.config/skhd/focus-window.sh next
cmd - k : ~/.config/skhd/focus-window.sh prev

ctrl + shift - 1 : yabai -m window --space 1 --focus
ctrl + shift - 2 : yabai -m window --space 2 --focus
ctrl + shift - 3 : yabai -m window --space 3 --focus
ctrl + shift - 4 : yabai -m window --space 4 --focus
ctrl + shift - 5 : yabai -m window --space 5 --focus
ctrl + shift - 6 : yabai -m window --space 6 --focus
ctrl + shift - 7 : yabai -m window --space 7 --focus
ctrl + shift - 8 : yabai -m window --space 8 --focus
ctrl + shift - 0 : yabai -m window --space 10 --focus

cmd - 0x2A : ~/.config/skhd/toggle-menubar.sh

cmd + shift - b : ~/.config/skhd/buku-picker.sh
