#!/usr/bin/env bash

# Source hardware config
source ~/.config/_vars/hardware.sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_created action="~/.config/yabai/window_created.sh"

# MOUSE
yabai -m config focus_follows_mouse autofocus
yabai -m config mouse_modifier cmd
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# LAYOUT
yabai -m config layout stack

# GAPS
yabai -m config top_padding 6
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 8
yabai -m config external_bar main:"$BAR_HEIGHT":0

# APPEARANCE
yabai -m config window_shadow off
