# app_name,icon,space (use - for current space)
Ghostty,󰆍,1
Rio,󰆍,1
Terminal,󰆍,1
WezTerm,󰆍,1

Brave Browser,,2
Ente Auth,󰦯,2

Xcode,,3
Zed,,3

zoom.us,,5

Slack,󰒱,6

Firefox,󰈹,7

Android Studio,󰀴,-
Bruno,󱂛,-
Calculator,,-
Code,,-
DBeaver,,-
Finder,󰇄,-
IINA,,-
LocalSend,󰒊,-
Postman,󱂛,-
Safari,,-
Simulator,,-
System Settings,,-
VimR,,-
