########################### TAPS ###########################

tap "asmvik/formulae"
tap "felixkratz/formulae"

########################### FONTS ###########################

cask "font-fira-code-nerd-font"
cask "font-sf-pro"
cask "sf-symbols"

########################### TERMINAL ###########################

# Terminal App
cask "ghostty"
cask "rio"
cask "wezterm@nightly"

# Terminal Workflow
brew "stow"
brew "trash-cli"

# CLI
brew "mise"
brew "aria2"
brew "pv"

# Neovim
brew "luarocks"
brew "luajit"

########################### DESKTOP ###########################

# Desktop Workflow
brew "local/yabai/yabai"
brew "skhd"
brew "borders"
brew "sketchybar"

# Desktop App
cask "brave-browser"
cask "ente-auth"
cask "firefox"
cask "iina"
cask "localsend"
cask "modern-csv"
cask "moonfin"
cask "slack"
cask "tailscale-app"
cask "zoom"

########################### DEVELOPMENT ###########################

# Dev Tools
brew "postgresql@16"
brew "redis"
cask "bruno"
cask "dbeaver-community"
cask "postman"
cask "visual-studio-code"
cask "zed"

# AI
brew "ollama"

# Xcode
brew "xcode-build-server"
brew "xcp"

# Docker
brew "docker-compose"
brew "docker-credential-helper"

# Virtualization
brew "e2fsprogs"
brew "qemu"

# Rails
brew "libpq"
brew "libyaml"

# AWS
brew "granted"
cask "session-manager-plugin"

# Network
brew "nmap"
brew "sshpass"
