#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Source colors
source ~/.config/_vars/colors.conf

##### Bar Appearance #####
sketchybar --bar position=top \
  color="$BAR_COLOR" \
  position=top \
  height=20 \
  notch_display_height=37.5 \
  margin=0 \
  y_offset=0 \
  corner_radius=0 \
  border_width=0 \
  blur_radius=0 \
  padding_left=10 \
  padding_right=10 \
  notch_width=200 \
  notch_offset=0 \
  display=all \
  hidden=off \
  topmost=window \
  sticky=on \
  font_smoothing=off \
  shadow=off # border_color=0xffff0000 \

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font.family="FiraCode Nerd Font"
  icon.font.style=SemiBold
  icon.font.size=18.0
  label.font.family="SF Pro Text"
  label.font.style=SemiBold
  label.font.size=14.0
  icon.color="$TEXT_PRIMARY"
  label.color="$TEXT_PRIMARY"
  icon.padding_left=6
  icon.padding_right=6
  label.padding_left=6
  label.padding_right=6
  background.drawing=off
)
sketchybar --default "${default[@]}"

##### Adding Items #####
ITEM_DIR="$CONFIG_DIR/items"

source "$ITEM_DIR/workspaces.sh"
source "$ITEM_DIR/app.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"

##### Force all scripts to run the first time #####
sketchybar --update
