#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Source colors
source "$PLUGIN_DIR/colors.sh"

##### Bar Appearance #####
sketchybar --bar position=top \
  color="$BAR_COLOR" \
  position=top \
  height=20 \
  notch_display_height=37.5 \
  margin=0 \
  y_offset=0 \
  corner_radius=0 \
  border_width=0 \
  blur_radius=0 \
  padding_left=10 \
  padding_right=10 \
  notch_width=200 \
  notch_offset=0 \
  display=all \
  hidden=off \
  topmost=window \
  sticky=on \
  font_smoothing=off \
  shadow=off # border_color=0xffff0000 \

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font.family="FiraCode Nerd Font"
  icon.font.style=SemiBold
  icon.font.size=18.0
  label.font.family="SF Pro Text"
  label.font.style=SemiBold
  label.font.size=14.0
  icon.color="$TEXT_PRIMARY"
  label.color="$TEXT_PRIMARY"
  icon.padding_left=6
  icon.padding_right=6
  label.padding_left=6
  label.padding_right=6
  background.drawing=off
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
SPACE_ICONS=("󰲠" "󰲢" "󰲤" "󰲦" "󰲨" "󰲪")
for i in "${!SPACE_ICONS[@]}"; do
  sid="$((i + 1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=0
    icon.padding_right=0
    icon.color="$TEXT_MUTED"
    icon.highlight_color="$ACCENT_PRIMARY"
    background.drawing=off
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
sketchybar --add item separator_left left \
  --set separator_left icon="|" \
  icon.color="$TEXT_MUTED" \
  padding_left=5 \
  padding_right=5 \
  label.drawing=off

sketchybar --add item chevron left \
  --set chevron icon=󰘍 \
  icon.color="$ACCENT_PRIMARY" \
  label.drawing=off \
  padding_left=5 \
  padding_right=5 \
  click_script="yabai -m space --focus recent"

sketchybar --add item front_app left \
  --set front_app icon=󰣆 \
  icon.color="$ACCENT_BLUE" \
  script="$PLUGIN_DIR/front_app.sh" \
  label.color="$TEXT_PRIMARY" \
  --subscribe front_app front_app_switched

##### Adding Right Items #####
sketchybar --add item clock right \
  --set clock update_freq=1 \
  icon=󰥔 \
  icon.color="$ACCENT_PURPLE" \
  script="$PLUGIN_DIR/clock.sh" \
  label.color="$TEXT_PRIMARY"

sketchybar --add item separator_right right \
  --set separator_right icon="|" \
  icon.color="$TEXT_MUTED" \
  padding_left=5 \
  padding_right=5 \
  label.drawing=off

sketchybar --add item wifi right \
  --set wifi script="$PLUGIN_DIR/wifi.sh" \
  icon.color="$ACCENT_BLUE" \
  label.color="$TEXT_PRIMARY" \
  update_freq=10 \
  --subscribe wifi wifi_change

sketchybar --add item battery right \
  --set battery update_freq=120 \
  script="$PLUGIN_DIR/battery.sh" \
  icon.color="$ACCENT_GREEN" \
  label.color="$TEXT_PRIMARY" \
  --subscribe battery system_woke power_source_change

sketchybar --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  icon.color="$ACCENT_CYAN" \
  label.color="$TEXT_PRIMARY" \
  --subscribe volume volume_change

##### Force all scripts to run the first time #####
sketchybar --update
