#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Source colors and hardware config
source ~/.config/_vars/colors.sh
source ~/.config/_vars/hardware.sh

##### Bar Appearance #####
sketchybar --bar position=top \
  color="$BACKGROUND_COLOR" \
  position=top \
  height="$BAR_HEIGHT" \
  margin=0 \
  y_offset=0 \
  corner_radius=0 \
  border_width=0 \
  blur_radius=0 \
  padding_left=15 \
  padding_right=15 \
  notch_width=200 \
  notch_offset=0 \
  display=all \
  hidden=off \
  topmost=window \
  sticky=on \
  font_smoothing=off \
  shadow=off # border_color=0xffff0000 \

##### Changing Defaults #####
default=(
  padding_left=1
  padding_right=1
  icon.align=center
  icon.font.family="FiraCode Nerd Font"
  icon.font.style=SemiBold
  icon.font.size="$ICON_FONT_SIZE"
  icon.color="$ACCENT_PRIMARY"
  label.align=center
  label.font.family="SF Pro Text"
  label.font.style=SemiBold
  label.font.size="$LABEL_FONT_SIZE"
  label.color="$TEXT_PRIMARY"
  label.padding_left=6
  label.padding_right=6
  background.drawing=off
)
sketchybar --default "${default[@]}"

##### Adding Items #####
ITEM_DIR="$CONFIG_DIR/items"

source "$ITEM_DIR/workspaces.sh"
source "$ITEM_DIR/app.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/layout.sh"
source "$ITEM_DIR/tailscale.sh"

##### Force all scripts to run the first time #####
sketchybar --update
