#!/bin/bash

# Source unified color palette
source ~/.config/_vars/colors.conf

options=(
	style=round
	width=6.0
	hidpi=off
	active_color="$ACCENT_PRIMARY"
	inactive_color="$TEXT_INACTIVE"
)

borders "${options[@]}"
